config/routes.rb
Rails
  .application
  .routes
  .draw do
    get '/' => 'user#new'
    get 'login' => 'user#login_form'
    post 'login' => 'user#login'
    get 'logout' => 'user#destroy'

    get 'user/index' => 'user#index'
    post 'user/create' => 'user#create'
    post 'user/:id/update' => 'user#update'
    get 'user/road/:id' => 'user#roadshow',as:'user_road'
    post 'study/create' => 'study#create'
    get 'study/index' => 'study#index'
    resources :tags do
      get 'study', to: 'study#search'
    end
    post 'study/:id/completed_create' => 'study#completed_create', as: 'completed_create'
    post 'study/:id/completed_destroy' => 'study#completed_destroy', as: 'completed_destroy'
    post 'study/:id/update' => 'study#update'
    post 'study/:id/destroy' => 'study#destroy'
    resources :user, only: [:new,:show,:edit]
    resources :study, only: [:new,:edit] do
      resources :like ,only: [:create,:destroy]
      resources :comment ,only: [:create]
    end
    get 'comment/index' => 'comment#index'
    get 'comment/:id/new' => 'comment#new',as: 'comment_new'
    get 'comment/:id' => 'comment#show',as: 'comment_show'
    get 'comment/:id/edit' => 'comment#edit',as: 'comment_edit'
    post 'comment/:id/update' => 'comment#update',as: 'comment_update'
    post 'comment/:id/destroy' => 'comment#destroy',as: 'comment_destroy'
    resources :guest_sessions, only: [:create]
  end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :comment_content, presence: true, length: { maximum: 140 }

  belongs_to :user
  belongs_to :study
  scope :order_desc, -> { order(id: :desc) }
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
  before_action :autheniticate_user, { only: %i[new edit update destroy] }
  before_action :not_set_current_user_comment, { only: [:edit] }
  before_action :set_comment, { only: %i[show edit update destroy] }
  def new
    @comment = Comment.new
    @study = Study.find(params[:id])
  end

  def create
    @comment = @current_user.comments.new(comment_params)
    if @comment.save
      flash[:success] = 'コメントを投稿しました！'
      redirect_to(comment_index_path)
    else
      flash[:alert] = 'コメントに不備があります'
      redirect_to(comment_new_path(@comment.study_id))
    end
  end

  def index
    @comments = Comment.all.order_desc.preload(:user, :study)
    @user = User.all
  end

  def show; end

  def edit; end

  def update
    @comment.update(comment_params)
    if @comment.save
      flash[:success] = 'コメントを編集しました！'
      redirect_to(comment_index_path)
    else
      flash[:alert] = 'コメントに不備があります'
      redirect_to(comment_edit_path(@comment.id))
    end
  end

  def destroy
    if @comment.destroy
      flash[:success] = 'コメントを削除しました！'
      redirect_to(comment_index_path)
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.permit(:comment_content, :study_id)
  end
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/views/comment/edit.html.erb
<div class="container user-edit-form">
    <div class="row">
        <%= form_with url:comment_update_path(@comment.id) do |form| %>
            <div class=" comment-form">
                <div class="form-group">
                    <%= form.label :comment_content ,'コメント編集',:class => 'comment-show-title'%>
                    <%= form.text_area :comment_content, :value=>@comment.comment_content,:class => 'comment-show-content' %>
                </div>
                <%= form.submit "保存" ,:class => 'btn btn-primary'%>
            </div>
        <% end %>
    </div>
</div>

app/views/comment/index.html.erb
<div class="container">
    <div class="row comment-container">
        <h1 class="comment-index-title">コメント一覧</h1>
        <% @comments.each do |comment|  %>
        <div class="comment-contents">
            <div class="col-md-8 ">
                <div class="comment-user">
                    <%if  comment.user.image_icon? %>
                        <img src="<%= comment.user.image_icon.url %>" class="u-image" alt="ユーザーアイコン">
                    <% else %>
                        <%= image_tag '/assets/default.jpeg' ,class:"u-image", :alt => 'ユーザーアイコン' %>
                    <% end %>
                    <%= link_to user_path(comment.user),class:"link-color comment-user-name" do %>
                        <p><%= comment.user.name%>さんがコメントしました</p>
                    <% end %>
                </div>
                <%= link_to comment_show_path(comment.id),class:"link-color" do %>
                    <p class="comment_text_content"><%= comment.comment_content %></p>
                <% end %>
            </div>
            <div class="col-md-4 comment-content">
                <%= link_to "/user/road/#{comment.study.user_id}",class:"link-color" do %>
                    <% @user.each do |user|%>
                    <% if user.id == comment.study.user_id %>
                        <p ><%= user.name %> さんの学習内容</p>
                    <% end %>
                    <% end %>
                    <p class="study-text">学習内容：<%= comment.study.content  %> </p>
                    <% if comment.study.material.empty? %>
                        <p class="study-text">学習教材：未定</p>
                    <% else %>
                    <p class="study-text">学習教材：<%= comment.study.material %></p>
                    <% end %>
                    <% if comment.study.period.nil? %>
                        <p class="study-text">学習完了日：未定</p>
                    <% else %>
                        <p class="study-text">学習完了日：<%= comment.study.period %>まで</p>
                    <% end %>
                <% end %>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/comment/new.html.erb
<div class="container">
    <div class="row">
        <%= form_with  url: "/study/#{@study.id}/comment",class: "f-studies" do |form| %>
            <div class="f-study comment-form">
                <div class="form-group">
                    <%= form.label :comment_content ,'コメントする！',:class => 'comment-title'%>
                    <%= form.text_area :comment_content,:value=>@comment.comment_content, :placeholder => "ロードマップや学習に対してコメントを送ってみよう！(140文字以内)",:class => 'comment-area'%>
                </div>
                <%= form.submit "作成" ,:class => 'study-btn'%>
            </div>
        <% end %>
    </div>
</div>

app/views/comment/show.html.erb
<div class="container user-edit-form">
    <div class="row">
        <h1 class="comment-show-title">コメント詳細</h1>
    <div class="comment-show-contents">
        <div class="comment-show-user">
            <div class="comment-show-icon">
                <%if  @comment.user.image_icon? %>
                    <img src="<%= @comment.user.image_icon.url %>" class="u-image" alt="ユーザーアイコン">
                <% else %>
                    <%= image_tag '/assets/default.jpeg' ,class:"u-image", :alt => 'ユーザーアイコン' %>
                <% end %>
            </div>
            <%= link_to user_path(@comment.user),class:"link-color comment-user-name" do %>
                <h3 class="commment-show-user-name"><%= @comment.user.name%></h3>
            <% end %>
        </div>
        <h3 class="comment-show-content"><%= @comment.comment_content %></h3>
    <% if @current_user.id == @comment.user.id%>
        <div class="study-edit-btns comment-show-btns">
            <%= link_to( "編集",comment_edit_path(@comment.id) ,class:"btn btn-primary study-edit-btn ") %>
            <%= link_to( "削除",comment_destroy_path(@comment.id) ,method: :post,class:"btn btn-primary study-edit-btn ") %>
        </div>
    <% end %>
    </div>
    </div>
</div>