config/routes.rb
Rails
  .application
  .routes
  .draw do
    get '/' => 'user#new'
    get 'login' => 'user#login_form'
    post 'login' => 'user#login'
    get 'logout' => 'user#destroy'

    get 'user/index' => 'user#index'
    post 'user/create' => 'user#create'
    post 'user/:id/update' => 'user#update'
    get 'user/road/:id' => 'user#roadshow',as:'user_road'
    post 'study/create' => 'study#create'
    get 'study/index' => 'study#index'
    resources :tags do
      get 'study', to: 'study#search'
    end
    post 'study/:id/completed_create' => 'study#completed_create', as: 'completed_create'
    post 'study/:id/completed_destroy' => 'study#completed_destroy', as: 'completed_destroy'
    post 'study/:id/update' => 'study#update'
    post 'study/:id/destroy' => 'study#destroy'
    resources :user, only: [:new,:show,:edit]
    resources :study, only: [:new,:edit] do
      resources :like ,only: [:create,:destroy]
      resources :comment ,only: [:create]
    end
    get 'comment/index' => 'comment#index'
    get 'comment/:id/new' => 'comment#new',as: 'comment_new'
    get 'comment/:id' => 'comment#show',as: 'comment_show'
    get 'comment/:id/edit' => 'comment#edit',as: 'comment_edit'
    post 'comment/:id/update' => 'comment#update',as: 'comment_update'
    post 'comment/:id/destroy' => 'comment#destroy',as: 'comment_destroy'
    resources :guest_sessions, only: [:create]
  end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  has_many :studies, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :name, presence: true
  validates :email,
            presence: true,
            format: {
              with: VALID_EMAIL_REGEX
            },
            uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, on: :create # 新規登録のみ有効、削除すると、User#updateのimage_iconでエラー発生する

  mount_uploader :image_icon, ImageUploader
end

app/controllers/user_controller.rb
# frozen_string_literal: true

class UserController < ApplicationController
  before_action :not_logout_user, { only: %i[login_form new] }
  before_action :not_set_current_user, { only: [:edit] }
  before_action :set_user, { only: %i[show edit update roadshow] }

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = '新規登録が完了しました！'
      redirect_to(user_path(@user))
    else
      render(new_user_path)
    end
  end

  def login_form; end

  def login
    @user = User.find_by(email: params[:email])
    if @user&.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:success] = 'ログインしました'
      redirect_to(user_path(@user))
    else
      @error_message = 'メールアドレスまたはパスワードが間違っています'
      @email = params[:email]
      @password = params[:password]
      render('user/login_form')
    end
  end

  def index
    @users = User.all
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
  end

  def show
    @study = Study.find_by(user_id: @user.id)
    @comments = Comment.all.order_desc.eager_load(:user, :study)
  end

  def edit; end

  def update
    @user.update(user_params)
    @user.image_icon = params[:image_icon] if params[:image_icon]
    if @user.save
      flash[:success] = 'ユーザー情報を編集できました！'
      redirect_to(user_path(@user))
    else
      flash.now[:alert] = '編集に誤りがあります'
      render('/user/edit')
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました'
    redirect_to(login_path)
  end

  def roadshow
    @studies = Study.where(user_id: @user.id).order_asc.preload(:tag_maps, :tags)
    @array_completed = @studies.pluck(:completed)
    @completed = completedCount(@array_completed)
  end

  def completedCount(array)
    result = [['達成', 0], ['未学習(学習中)', 0]]
    array.each do |i|
      if i == @current_user.id
        result[0][1] += 1
      else
        result[1][1] += 1
      end
    end
    result
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.permit(:name, :email, :goal, :password, :image_icon)
  end
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
  def goal_text(_user)
    if @user.goal.blank?
      'まだ決めていません！'
    else
      @user.goal
    end
  end
end

app/views/user/_login_text.html.erb
<div class="col-md-8 text-left">
    <h2>ShareRoadMapへようこそ！</h2>
    <p>目標へのロードマップを作成してシェアしよう！ <br> 情報を共有して正しい学習手順を見つけ出そう！！</p>
</div>

app/views/user/_user_prof.html.erb
<%if  @user.image_icon? %>
    <img src="<%= @user.image_icon.url %>" class="img-icon" alt="ユーザーアイコン">
    <% else %>
    <%= image_tag '/assets/default.jpeg' ,class:"img-icon", :alt => 'ユーザーアイコン' %>
<% end %>
<div class="user-text">
    <h5 class="user-name"><%= @user.name %></h5>
    <% if current_user?(@user.id) %>
        <%= link_to("編集", edit_user_path(@user),class:"user-edit-btn btn btn-primary") %>
    <% end %>
</div>

app/views/user/edit.html.erb
<div class="container user-edit-form">
    <div class="row">
        <%= form_with url:"/user/#{@user.id}/update" do |form| %>
            <div class="edit-form">
                <h2>アカウント編集</h2>
                <div class="form-group">
                    <%= form.label :name ,'ユーザー名',:class => 'form-label'%>
                    <%= form.text_field :name, :value=>@user.name,:class => 'form-control' %>
                </div>
                <div class="form-group">
                    <%= form.label :image_icon ,'アイコン画像',:class => 'form-label'%>
                    <%= form.file_field :image_icon  %>
                </div>
                <div class="form-group">
                    <%= form.label :email ,'メールアドレス',:class => 'form-label'%>
                    <%= form.text_field :email, :value=>@user.email,:class => 'form-control' %>
                </div>
                <div class="form-group">
                    <%= form.label :goal ,'目標設定',:class => 'form-label'%>
                    <%= form.text_field :goal, :value=>@user.goal,:class => 'form-control', :placeholder => "明確な目標を設定しよう！" %>
                </div>
                <%= form.submit "保存" ,:class => 'btn btn-primary'%>
            </div>
        <% end %>
    </div>
</div>

app/views/user/index.html.erb
<div class="container u-container">
    <div class="row user-index">
        <div class="col-sm-9">
            <div class="u-contents">
                <% @users.each do |user| %>
                    <div class="u-content">
                        <div class="u-content-left">
                        <%if  user.image_icon? %>
                            <img src="<%= user.image_icon.url %>" class="u-image" alt="ユーザーアイコン">
                        <% else %>
                            <%= image_tag '/assets/default.jpeg' ,class:"u-image", :alt => 'ユーザーアイコン' %>
                        <% end %>
                        </div>
                        <div class="u-content-right">
                            <%= link_to( user.name ,user_path(user), {class: "u-name"}) %>
                            <% if user.goal %>
                                <%= link_to(  "目標：#{user.goal}" , user_road_path(user), {class: "u-goal"}) %>
                            <% else %>
                                <%= link_to( "目標はまだ決めていません！" , user_road_path(user), {class: "u-goal"}) %>
                            <% end %>
                        </div>
                    </div>
                <% end %>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="search-form">
                <%= search_form_for @q ,url: user_index_path do |f| %>
                        <div class="search-field">
                            <%= f.search_field :name_or_goal_cont , :placeholder => "目標を検索してみよう"%>
                            <%= f.submit "検索" %>
                        </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/user/login_form.html.erb
<div class="jumbotron">
    <div class="container">
    <div class="row fv-content">
        <%= render :partial => "login_text" %>
        <div class="col-md-4 form-text">
            <%= form_tag("/login" ,{method: "post"}) do %>
                <% if @error_message %>
                    <div class="form-error">
                        <%= @error_message %>
                    </div>
                <% end %>
                    <h4>ログイン</h4>
                    <div class="form-group">
                        <label class="form-label">メールアドレス</label>
                        <input type="email"  name="email" class="form-control" value="<%= @email %>">
                    </div>
                    <div class="form-group">
                        <label class="form-label">パスワード</label>
                        <input type="password"  name="password" class="form-control" value="<%= @password %>">
                    </div>
                    <button type="submit"  class="btn btn-primary">ログイン</button>
            <% end %>
        </div>
    </div>
    </div>
</div>

app/views/user/new.html.erb
<div class="jumbotron">
    <div class="container">
    <div class="row fv-content">
        <%= render :partial => "login_text" %>
        <div class="col-md-4 form-text">
            <%= form_with model:@user ,url:user_create_path do |form|  %>
                <% @user.errors.full_messages.each do |message| %>
                    <%= message %>
                <% end %>
                    <h4>新規登録</h4>
                    <div class="form-group">
                        <label class="form-label">ユーザー名</label>
                        <input type="name" name="name" class="form-control" value="<%= @user.name %>">
                    </div>
                    <div class="form-group">
                        <label class="form-label">メールアドレス</label>
                        <input type="email" name="email" class="form-control" value="<%= @user.email %>">
                    </div>
                    <div class="form-group">
                    　  <label class="form-label">パスワード</label>
                        <input type="password" name="password" class="form-control" value="<%= @user.password %>">
                    </div>
                    <input type="submit" class="btn btn-primary" value="登録">
            <% end %>
        </div>
    </div>
    </div>
</div>

app/views/user/roadshow.html.erb
<div class="container road-container">
    <div class="row">
        <h3 class="g-text">目標は<%= goal_text(@user.goal) %> </h3>
        <% if @studies.empty? %>
            <div class="n-studies">
                <h3 class="n-studies-title">ロードマップは未作成です</h3>
                <% if @current_user== @user%>
                    <%= link_to( "作成する！",new_study_path,class:"user-edit-btn btn btn-primary r-btn" ) %>
                <% end %>
            </div>
        <% else %>
        <%= link_to(  "#{@user.name}さんのロードマップ" , user_path(@user), class: "study-title link-color") %>
        <div class="row studies">
            <div class="col-md-6">
                <% @studies.each.with_index(1) do |study,i| %>
                        <div class="d-flex flex-row study-contents">
                            <div class="study-content">
                                <div class="study-numbers">
                                    <h4 class="study-text study-num"><%= i %></h4>
                                </div>
                                <h4 class="study-text">学習内容：<%= study.content  %> </h4>
                                <h4 class="study-text">
                                    <%= study_material(study) %>
                                </h4>
                                <h4 class="study-text">
                                    <%= study_period(study) %>
                                </h4>
                                <% if current_user?(@user.id)%>
                                    <div class="study-edit-btns">
                                        <%= link_to( "編集",edit_study_path(study) ,class:"btn btn-primary study-edit-btn ") %>
                                        <%= link_to("削除" ,"/study/#{study.id}/destroy",class:"btn btn-primary study-edit-btn",method: :post)%>
                                    </div>
                                <% end %>
                                <div class="icons">
                                    <% study.tags.each do |list| %>
                                        <span class="tags"><%= list.tag_name %></span>
                                    <% end %>
                                    <%= link_to comment_new_path(study.id),class:"link-color " do %>
                                        <i class="far fa-comment comment-icon"></i>
                                    <% end %>
                                    <% if study.liked_by?(@current_user) %>
                                        <%= link_to study_like_path(study.id),method: :delete,class:"like_btn" do %>
                                            <i class="far fa-heart liked"></i>
                                            <span><%= study.likes.count %></span>
                                        <% end %>
                                    <% else %>
                                        <%=link_to "/study/#{study.id}/like", method: :post ,class:"like_btn" do %>
                                            <i class="fas fa-heart"></i>
                                            <span><%= study.likes.count %></span>
                                        <% end %>
                                    <% end %>
                                    <% if  study.completed.nil? %>
                                        <%= link_to completed_create_path(study) , method: :post  do %>
                                            <i class="far fa-check-circle check complete"></i>
                                        <% end %>
                                    <% else %>
                                        <%= link_to completed_destroy_path(study) , method: :post do %>
                                        <i class="far fa-check-circle  check completed"></i>
                                        <% end %>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                <% end %>
            </div>
            <div class="col-md-6">
                <% if  current_user?(@user.id) %>
                    <div class="add-study-btn">
                        <%= link_to( "追加","/study/new",class:"btn btn-primary study_add_btn" ) %>
                    </div>
                <% end %>
                <%= link_to("学習投稿一覧",study_index_path, {class: "link-color btn btn-primary  study_index_btn"}) %>
                <% end %>
                <%= pie_chart @completed , title: "学習達成度",colors: ["#3CB371", "#FF4F50"] %>
            </div>
        </div>
    </div>
</div>

app/views/user/show.html.erb
<div class="container">
  <div class="row user-show">
    <div class="col-md-6">
      <div class="user-content">
          <%= render 'user_prof' %>
        <h3 class="g-text">目標：<%= goal_text(@user.goal) %> </h3>
        <%= link_to("ロードマップをみる","/user/road/#{@user.id}",class:"user-edit-btn btn btn-primary") %>
      </div>
    </div>
    <div class="col-md-6">
    <h1 class="user-show-comment-title">届いたコメント</h1>
    <% if @study %>
      <% @comments.each do |comment|  %>
        <% if comment.study.user_id == @study.user_id %>
          <div class="comment-contents user-show-comment-contents">
                <div class="comment-user ">
                    <%if  comment.user.image_icon? %>
                        <img src="<%= comment.user.image_icon.url %>" class="u-image" alt="ユーザーアイコン">
                    <% else %>
                        <%= image_tag '/assets/default.jpeg' ,class:"u-image", :alt => 'ユーザーアイコン' %>
                    <% end %>
                    <%= link_to user_path(comment.user),class:"link-color comment-user-name" do %>
                        <p><%= comment.user.name%>さんがコメントしました</p>
                    <% end %>
                </div>
                <%= link_to "/user/road/#{@user.id}",class:"link-color" do %>
                  <p class="study-text">学習内容：<%= comment.study.content  %> に対してのコメント</p>
                <% end %>
                <%= link_to comment_show_path(comment.id),class:"link-color" do %>
                    <p class="comment_text_content"><%= comment.comment_content %></p>
                <% end %>
          </div>
        <% end %>
      <% end %>
    <% end %>
    </div>
  </div>
</div>

app/views/user/signup.html.erb
<div class="jumbotron">
    <div class="container">
    <div class="row fv-content">
        <div class="col-md-6 text-left">
        <h3>ShareRoadMapへようこそ！</h3>
        <p>目標へのロードマップを計画・作成してシェアしよう！ <br> 情報を共有して目標への最短距離を見つけ出そう！！</p>
        </div>
        <div class="col-md-6">
        <form class="form">
        <h4>新規登録</h4>
            <div class="form-group">
                <input type="name" class="form-control" placeholder="ユーザー名">
            </div>
            <div class="form-group">
                <input type="email" class="form-control"aria-describedby="emailHelp" placeholder="メールアドレス">
            </div>
            <div class="form-group">
                <input type="password" class="form-control" placeholder="パスワード">
            </div>
            <button type="submit" class="btn btn-primary">登録</button>
        </form>
        </div>
    </div>
    </div>
</div>