config/routes.rb
Rails
  .application
  .routes
  .draw do
    get '/' => 'user#new'
    get 'login' => 'user#login_form'
    post 'login' => 'user#login'
    get 'logout' => 'user#destroy'

    get 'user/index' => 'user#index'
    post 'user/create' => 'user#create'
    post 'user/:id/update' => 'user#update'
    get 'user/road/:id' => 'user#roadshow',as:'user_road'
    post 'study/create' => 'study#create'
    get 'study/index' => 'study#index'
    resources :tags do
      get 'study', to: 'study#search'
    end
    post 'study/:id/completed_create' => 'study#completed_create', as: 'completed_create'
    post 'study/:id/completed_destroy' => 'study#completed_destroy', as: 'completed_destroy'
    post 'study/:id/update' => 'study#update'
    post 'study/:id/destroy' => 'study#destroy'
    resources :user, only: [:new,:show,:edit]
    resources :study, only: [:new,:edit] do
      resources :like ,only: [:create,:destroy]
      resources :comment ,only: [:create]
    end
    get 'comment/index' => 'comment#index'
    get 'comment/:id/new' => 'comment#new',as: 'comment_new'
    get 'comment/:id' => 'comment#show',as: 'comment_show'
    get 'comment/:id/edit' => 'comment#edit',as: 'comment_edit'
    post 'comment/:id/update' => 'comment#update',as: 'comment_update'
    post 'comment/:id/destroy' => 'comment#destroy',as: 'comment_destroy'
    resources :guest_sessions, only: [:create]
  end

app/models/study.rb
# frozen_string_literal: true

class Study < ApplicationRecord
  validates :content, presence: true
  validates :user_id, presence: true
  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :tag_maps, dependent: :destroy
  has_many :tags, through: :tag_maps # 投稿に紐づけられたタグを取得することができる
  scope :order_asc, -> { order(id: :asc) }
  scope :order_desc, -> { order(id: :desc) }

  def liked_by?(user)
    likes.where(user_id: user.id).exists?
  end

  # 編集する際に古いタグを削除する必要があるため、この処理が必要になる
  def save_studies(sent_tags)
    # 学習が投稿されたときにtag_nameが存在する場合、current_tagsに配列として全て代入される
    current_tags = tags.pluck(:tag_name) unless tags.nil?
    # 投稿された時のタグを除いたタグをold_tagsとする
    old_tags = current_tags - sent_tags
    # 現在存在するタグを除いた新しいタグをnew_tagsに代入
    new_tags = sent_tags - current_tags

    # 古いタグを削除
    old_tags.each do |old|
      tags.delete Tag.find_by(tag_name: old)
    end

    # 新しいタグをDBに保存
    new_tags.each do |new|
      new_study_tag = Tag.find_or_create_by(tag_name: new.downcase)
      # 配列に保存
      tags << new_study_tag
    end
  end
end

app/controllers/study_controller.rb
# frozen_string_literal: true

class StudyController < ApplicationController
  before_action :autheniticate_user, { only: %i[new index search edit completed_create completed_destroy] }
  before_action :not_set_current_user_study, { only: [:edit] }
  before_action :not_set_current_user_complete, { only: %i[completed_create completed_destroy] }
  before_action :set_study, { only: %i[completed_create completed_destroy edit update destroy] }
  before_action :set_tag, { only: %i[index search] }
  def new
    @studies = Study.new
  end

  def create
    @studies = Study.new(study_params)
    tag_list = params[:tag_name].split(/[[:blank:]]+/)
    if @studies.save
      @studies.save_studies(tag_list)
      flash[:success] = '学習を追加しました！'
      redirect_to("/user/road/#{@studies.user_id}")
    else
      render('/study/new')
    end
  end

  def index
    @user = User.all
    @studies = Study.all.order_desc.preload(:user, :tag_maps, :tags)
  end

  def search
    @tag = Tag.find(params[:tag_id])
    @studies = @tag.studies.all.preload(:user, :tag_maps, :tags)
  end

  def completed_create
    completed = @study.update(completed: @current_user.id)
    flash[:success] = '達成おめでとう！!'
    redirect_to("/user/road/#{@study.user_id}")
  end

  def completed_destroy
    completed = @study.update(completed: nil)
    redirect_to("/user/road/#{@study.user_id}")
  end

  def edit
    @tag_list = @study.tags.pluck(:tag_name)
  end

  def update
    @study.update(study_params)
    tag_list = params[:tag_name].split(/[[:blank:]]+/)
    if @study.save
      @study.save_studies(tag_list)
      flash[:success] = '学習を編集しました！'
      redirect_to("/user/road/#{@study.user_id}")
    else
      render('study/edit')
    end
  end

  def destroy
    if @study.destroy
      flash[:success] = '学習を削除しました！'
      redirect_to("/user/road/#{@study.user_id}")
    end
  end

  private

  def set_tag
    @tag_list = Tag.all
  end

  def set_study
    @study = Study.find(params[:id])
  end

  def study_params
    params.permit(:content, :material, :period, :tag_list).merge(user_id: @current_user.id)
  end
end

app/helpers/study_helper.rb
# frozen_string_literal: true

module StudyHelper
  def study_material(study)
    if study.material.empty?
      '学習教材：未定'
    else
      "学習教材：#{study.material}"
    end
  end

  def study_period(study)
    if study.period.nil?
      '学習完了予定日：未定'
    else
      "学習完了予定日：#{study.period}まで"
    end
  end
end

app/views/study/edit.html.erb
<div class="container">
    <div class="row ">
        <%= form_with url:"/study/#{@study.id}/update" , class: "f-studies" do |form| %>
            <div class="f-study">
                <% @study.errors.full_messages.each do |message| %>
                    <%= message %>
                <% end %>
                <div class="form-group">
                    <%= form.label :content ,'学習内容',:class => 'label-study'%>
                    <%= form.text_field :content, :value=>@study.content %>
                </div>
                <div class="form-group">
                    <%= form.label :material ,'学習教材',:class =>'label-study'%>
                    <%= form.text_field :material, :value=>@study.material %>
                </div>
                <div class="form-group">
                    <%= form.label :period ,'学習完了日' ,:class => 'label-study'%>
                    <%= form.date_field :period, :value=>@study.period %>
                </div>
                <div class="form-group">
                    <%= form.label :tag_name ,'タグ' ,:class => 'label-study'%>
                    <%= form.text_field :tag_name, :value=>@tag_list, :placeholder => "複数の場合は、スペースを開けて入力して下さい"%>
                </div>
            </div>
            <div class="study-edit-btn">
                <%= form.submit "保存" ,:class => 'edit-btn'%>
            </div>
        <% end %>
    </div>
</div>

app/views/study/index.html.erb
<div class="container study-index-container">
        <h1>学習投稿一覧</h1>
    <div class="row">
        <div class="col-md-8 study-index">
            <% @studies.each do |study| %>
                <div class="study-contents">
                    <div class="study-content">
                        <%= link_to( "#{study.user.name}さんの学習内容" ,user_path(study.user_id), {class: "link-color"}) %>
                        <%= link_to user_road_path(study.user_id),class:"link-color" do %>
                            <h4 class="study-text">学習内容：<%= study.content  %> </h4>
                            <h4 class="study-text">
                                <%= study_material(study) %>
                            </h4>
                            <h4 class="study-text">
                                <%= study_period(study) %>
                            </h4>
                            <% study.tags.each do |list| %>
                                    <span class="tags"><%= list.tag_name %></span>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            <% end %>
        </div>
        <div class="col-md-4">
            <h1>タグ一覧</h1>
            <% @tag_list.each do |list|%>
                <%= link_to tag_study_path(tag_id: list.id),class:"link-color" do %>
                    <span class="tags study-index-tags"><%= list.tag_name %></span>
                <% end %>
            <% end %>
        </div>
    </div>
</div>

app/views/study/new.html.erb
<div class="container">
    <div class="row">
        <%= form_with  url: "/study/create",class: "f-studies" do |form| %>
            <div class="f-study">
                <% @studies.errors.full_messages.each do |message| %>
                    <%= message %>
                <% end %>
                <div class="form-group">
                    <%= form.label :content ,'学習内容',:class => 'label-study'%>
                    <%= form.text_field :content,:value=>@studies.content, :placeholder => "学習する内容を記入しよう！"%>
                </div>
                <div class="form-group">
                    <%= form.label :material ,'学習教材',:class =>'label-study'%>
                    <%= form.text_field :material,:value=>@studies.material , :placeholder => "学習に使用する教材を決めよう！"%>
                </div>
                <div class="form-group">
                    <%= form.label :period ,'学習完了日' ,:class => 'label-study'%>
                    <%= form.date_field :period ,:value=>@studies.period%>
                </div>
                <div class="form-group">
                    <%= form.label :tag_name ,'タグ' ,:class => 'label-study'%>
                    <%= form.text_field :tag_name,:value=>@tag_list,:placeholder => "複数の場合は、スペースを開けて入力して下さい"%>
                </div>
                <%= form.submit "作成" ,:class => 'study-btn'%>
            </div>
        <% end %>
    </div>
</div>

app/views/study/search.html.erb
<div class="container study-index-container">
        <h2><%= @tag.tag_name %>の検索一覧</h2>
    <div class="row">
        <div class="col-md-8 study-index">
            <% @studies.each do |study| %>
                <div class="study-contents">
                    <div class="study-content">
                        <%= link_to( "#{study.user.name}さんの学習内容" ,user_path(study.user_id), {class: "link-color"}) %>
                        <%= link_to user_road_path(study.user_id),class:"link-color" do %>
                            <h4 class="study-text">学習内容：<%= study.content  %> </h4>
                            <h4 class="study-text">
                                <%= study_material(study) %>
                            </h4>
                            <h4 class="study-text">
                                <%= study_period(study) %>
                            </h4>
                            <% study.tags.each do |list| %>
                                    <span class="tags"><%= list.tag_name %></span>
                            <% end %>
                        <% end %>
                    </div>
                </div>
            <% end %>
        </div>
        <div class="col-md-4">
            <h1>タグ一覧</h1>
            <% @tag_list.each do |list|%>
                <%= link_to tag_study_path(tag_id: list.id),class:"link-color" do %>
                    <span class="tags study-index-tags"><%= list.tag_name %></span>
                <% end %>
            <% end %> <br>
            <%= link_to("学習投稿一覧に戻る",study_index_path, {class: "link-color"}) %>
        </div>
    </div>
</div>