config/routes.rb
Rails
  .application
  .routes
  .draw do
    get '/' => 'user#new'
    get 'login' => 'user#login_form'
    post 'login' => 'user#login'
    get 'logout' => 'user#destroy'

    get 'user/index' => 'user#index'
    post 'user/create' => 'user#create'
    post 'user/:id/update' => 'user#update'
    get 'user/road/:id' => 'user#roadshow',as:'user_road'
    post 'study/create' => 'study#create'
    get 'study/index' => 'study#index'
    resources :tags do
      get 'study', to: 'study#search'
    end
    post 'study/:id/completed_create' => 'study#completed_create', as: 'completed_create'
    post 'study/:id/completed_destroy' => 'study#completed_destroy', as: 'completed_destroy'
    post 'study/:id/update' => 'study#update'
    post 'study/:id/destroy' => 'study#destroy'
    resources :user, only: [:new,:show,:edit]
    resources :study, only: [:new,:edit] do
      resources :like ,only: [:create,:destroy]
      resources :comment ,only: [:create]
    end
    get 'comment/index' => 'comment#index'
    get 'comment/:id/new' => 'comment#new',as: 'comment_new'
    get 'comment/:id' => 'comment#show',as: 'comment_show'
    get 'comment/:id/edit' => 'comment#edit',as: 'comment_edit'
    post 'comment/:id/update' => 'comment#update',as: 'comment_update'
    post 'comment/:id/destroy' => 'comment#destroy',as: 'comment_destroy'
    resources :guest_sessions, only: [:create]
  end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareRoadMap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= javascript_pack_tag 'application'%>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>

  <body>
    <header>
      <% if @current_user %>
        <div class="login-hd">
        <%= link_to("ShareRoadMap","/user/road/#{@current_user.id}",class:"logo") %>
            <ul class="nav justify-content-end">
                <li class="nav-item">
                  <%= link_to(@current_user.name,user_path(@current_user),class:"nav-text") %>
                </li>
                <li class="nav-item">
                  <%= link_to("コメント一覧",comment_index_path,class:"nav-text") %>
                </li>
                <li class="nav-item">
                <%= link_to("ユーザー一覧", user_index_path,class:"nav-text") %>
                </li>
                <li class="nav-item">
                  <%= link_to("ログアウト", logout_path,class:"nav-text") %>
                </li>
            </ul>
        </div>
      <% else %>
      <div class="logout-hd">
        <%= link_to("ShareroadMap",new_user_path,class:"logo") %>
        <ul class="nav justify-content-end">
            <li class="nav-item">
              <%= link_to("新規登録", new_user_path) %>
            </li>
            <li class="nav-item">
            <%= link_to("ログイン", login_path) %>
            </li>
            <li class="nav-item">
            <%= link_to("ゲストログイン", guest_sessions_path,method: :post) %>
            </li>
        </ul>
      </div>
      <% end %>
    </header>
    <% if flash[:alert] %>
      <div class="alert">
        <% flash.each do |alert, message| %>
          <%= message %>
        <% end %>
      </div>
    <% end %>
    <% if flash[:success] %>
      <div class="success">
        <% flash.each do |success, message| %>
          <%= message %>
        <% end %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>